### ISSUE TITLE
Not setting property - error in console

### ISSUE THREAD

**Issue by edgegamers** [FXServer-ESX/fxserver-esx_property#1]
[   1101531] Error running system event handling function for resource esx_property: citizen:/scripting/lua/scheduler.lua:39: Failed to execute thread: client/main.lua:204: attempt to index a nil value (local 'gateway')
[   1101531] stack traceback:
[   1101547] 	client/main.lua:204: in function 'SetPropertyOwned'
[   1101547] 	client/main.lua:838: in upvalue 'handler'
[   1101547] 	citizen:/scripting/lua/scheduler.lua:124: in function <citizen:/scripting/lua/scheduler.lua:123>
[   1101562] stack traceback:
[   1101562] 	[C]: in function 'error'
[   1101562] 	citizen:/scripting/lua/scheduler.lua:39: in field 'CreateThreadNow'
[   1101578] 	citizen:/scripting/lua/scheduler.lua:123: in function <citizen:/scripting/lua/scheduler.lua:92>
[   1117078] EndpointMapper::HandleRequest: POST /gta5/11/gameservices/GeoLocation.asmx/GetLocationInfoFromIP

**Comment by edgegamers** [comment]
Agent gives me the apartment, says it takes money out but doesn't and no error in console

http://i.imgur.com/fHaIjsi.jpg

Not sure if this is related

**Comment by indilo53** [comment]
For which property ?

**Comment by indilo53** [comment]
Have you restarted the resource ?

**Comment by edgegamers** [comment]
Not sure if the player was bugged, but they logged out of the server and then back on and was able to set the property. Though when they do, money does not get removed from the player buying the property. We get a notification, but no money is removed.

**Comment by indilo53** [comment]
Fixed in https://github.com/FXServer-ESX/fxserver-esx_realestateagentjob/commit/eba26ffd18407da30e1f223fcefe2f3c88df2059
